import{apiSlice}from'./apiSlice';
import{uniqueById}from'../../utils/uniqueById';
export type CustomerOrderNotificationType='ORDER_PLACED'|'ORDER_ACCEPTED'|'ORDER_PREPARING'|'ORDER_READY'|'ORDER_PICKED_UP'|'OUT_FOR_DELIVERY'|'ORDER_DELIVERED'|'ORDER_CANCELLED'|'PAYMENT_VERIFIED'|'PAYMENT_REJECTED';
export interface CustomerOrderNotification{_id:string;notificationId:string;title:string;message:string;type:CustomerOrderNotificationType;orderStatus:string;isRead:boolean;createdAt:string;restaurantId:null|{_id:string;name:string;image?:string};orderId:null|{_id:string;orderNumber:string;orderStatus:string;deliveryStatus?:string}}
interface NotificationResponse{success:boolean;data:{notifications:CustomerOrderNotification[];unreadCount:number;pagination:{page:number;limit:number;total:number;pages:number}}}
interface ReadDisplayedResponse{success:boolean;data:{updatedCount:number;unreadCount:number}}
export const customerOrderNotificationApi=apiSlice.injectEndpoints({endpoints:b=>({
 getCustomerOrderNotifications:b.query<NotificationResponse,void>({query:()=>({url:'/customer-order-notifications',params:{limit:50}}),transformResponse:(response:NotificationResponse)=>({...response,data:{...response.data,notifications:uniqueById(response.data.notifications)}}),providesTags:['CustomerOrderNotification' as any]}),
 readCustomerOrderNotification:b.mutation<any,string>({query:id=>({url:`/customer-order-notifications/${id}/read`,method:'PATCH'}),invalidatesTags:['CustomerOrderNotification' as any]}),
 readDisplayedCustomerOrderNotifications:b.mutation<ReadDisplayedResponse,string[]>({query:ids=>({url:'/customer-order-notifications/read',method:'PATCH',body:{ids}}),async onQueryStarted(ids,{dispatch,queryFulfilled}){const idSet=new Set(ids);const patch=dispatch(customerOrderNotificationApi.util.updateQueryData('getCustomerOrderNotifications',undefined,draft=>{let changed=0;draft.data.notifications.forEach(item=>{if(idSet.has(item._id)&&!item.isRead){item.isRead=true;changed+=1}});draft.data.unreadCount=Math.max(0,draft.data.unreadCount-changed)}));try{const{data}=await queryFulfilled;dispatch(customerOrderNotificationApi.util.updateQueryData('getCustomerOrderNotifications',undefined,draft=>{draft.data.unreadCount=data.data.unreadCount}))}catch{patch.undo()}},invalidatesTags:['CustomerOrderNotification' as any]}),
 deleteCustomerOrderNotification:b.mutation<any,string>({query:id=>({url:`/customer-order-notifications/${id}`,method:'DELETE'}),invalidatesTags:['CustomerOrderNotification' as any]}),
 deleteReadCustomerOrderNotifications:b.mutation<any,void>({query:()=>({url:'/customer-order-notifications/read',method:'DELETE'}),invalidatesTags:['CustomerOrderNotification' as any]})
})});
export const{useGetCustomerOrderNotificationsQuery,useReadCustomerOrderNotificationMutation,useReadDisplayedCustomerOrderNotificationsMutation,useDeleteCustomerOrderNotificationMutation,useDeleteReadCustomerOrderNotificationsMutation}=customerOrderNotificationApi;
