import React from 'react';

export const BarChart: React.FC<{ data: Array<{ label: string; value: number }>; color?: string; currency?: boolean; empty?: string }> = ({ data, color = '#f97316', currency, empty = 'No data for this period' }) => {
  const max = Math.max(...data.map(item => item.value), 0);
  if (!data.length || max === 0) return <div className="h-52 grid place-items-center text-sm text-white/35">{empty}</div>;
  return <div className="h-60 flex items-end gap-2 sm:gap-3 pt-8">{data.map((item, index) => <div key={`${item.label}-${index}`} className="group flex-1 h-full flex flex-col justify-end items-center min-w-0"><div className="relative w-full max-w-12 rounded-t-lg transition-all duration-700 group-hover:brightness-125" style={{ height: `${Math.max(4, item.value / max * 82)}%`, background: `linear-gradient(to top, ${color}88, ${color})` }}><span className="absolute opacity-0 group-hover:opacity-100 -top-8 left-1/2 -translate-x-1/2 whitespace-nowrap text-[10px] bg-dark-300 px-2 py-1 rounded">{currency ? '৳' : ''}{item.value.toLocaleString(undefined, { maximumFractionDigits: 0 })}</span></div><span className="text-[10px] sm:text-xs text-white/40 mt-2 truncate w-full text-center">{item.label}</span></div>)}</div>;
};

export const HorizontalBars: React.FC<{ data: Array<{ name: string; value: number }>; suffix?: string }> = ({ data, suffix = '' }) => { const max = Math.max(...data.map(item => item.value), 0); return <div className="space-y-4 mt-5">{!data.length && <div className="h-36 grid place-items-center text-sm text-white/35">No food performance yet</div>}{data.map(item => <div key={item.name}><div className="flex justify-between text-xs mb-2"><span className="truncate pr-3">{item.name}</span><b>{item.value.toFixed(suffix ? 1 : 0)}{suffix}</b></div><div className="h-2 bg-white/10 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-primary-600 to-secondary-500 rounded-full transition-all duration-700" style={{ width: `${max ? item.value / max * 100 : 0}%` }} /></div></div>)}</div>; };

export const DonutChart: React.FC<{ values: Array<{ label: string; value: number; color: string }> }> = ({ values }) => { const total = values.reduce((sum, item) => sum + item.value, 0); let cursor = 0; const gradient = values.map(item => { const start = cursor; cursor += total ? item.value / total * 100 : 0; return `${item.color} ${start}% ${cursor}%`; }).join(','); return <div className="flex flex-col sm:flex-row items-center justify-center gap-8 h-60"><div className="w-36 h-36 rounded-full grid place-items-center" style={{ background: total ? `conic-gradient(${gradient})` : 'rgba(255,255,255,.08)' }}><div className="w-24 h-24 rounded-full bg-dark-100 grid place-items-center"><div className="text-center"><b className="text-2xl">{total}</b><span className="block text-[10px] text-white/40">ORDERS</span></div></div></div><div className="grid grid-cols-2 gap-x-5 gap-y-2">{values.map(item => <div key={item.label} className="text-xs flex items-center gap-2"><i className="w-2.5 h-2.5 rounded-full" style={{ background: item.color }} />{item.label} <b>{item.value}</b></div>)}</div></div>; };
