import React, { useEffect, useRef, useState } from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { Copy, Crosshair, Expand, ExternalLink, LoaderCircle, MapPin, Search } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { useLazySearchLocationsQuery, useReverseLocationMutation, type LocationResult } from '../../store/api/locationApi';

export interface RestaurantAddress { restaurantAddress?:string;area?:string;street:string;city:string;district?:string;state:string;zipCode:string;country:string;coordinates:{lat?:number;lng?:number} }
const fallback:[number,number]=[23.8103,90.4125];
const pin=L.divIcon({className:'',html:'<div style="width:30px;height:30px;background:#f97316;border:4px solid white;border-radius:50% 50% 50% 0;transform:rotate(-45deg);box-shadow:0 0 22px rgba(249,115,22,.8)"><i style="display:block;width:8px;height:8px;background:white;border-radius:50%;margin:7px"></i></div>',iconSize:[30,30],iconAnchor:[15,30]});

const RestaurantLocationPicker:React.FC<{value:RestaurantAddress;onChange:(value:RestaurantAddress)=>void}>=({value,onChange})=>{
  const mapNode=useRef<HTMLDivElement>(null); const map=useRef<L.Map|undefined>(undefined); const marker=useRef<L.Marker|undefined>(undefined);
  const[query,setQuery]=useState(''); const[debounced,setDebounced]=useState(''); const[locating,setLocating]=useState(false); const[geocoding,setGeocoding]=useState(false);
  const[pendingMarker,setPendingMarker]=useState<{lat:number;lng:number}|null>(null); const[accuracy,setAccuracy]=useState<number|null>(null);
  const[search,{data,isFetching}]=useLazySearchLocationsQuery(); const[reverse]=useReverseLocationMutation();
  const apply=(result:LocationResult)=>{setPendingMarker(null);onChange({restaurantAddress:result.restaurantAddress||result.displayName,area:result.area,street:result.restaurantAddress||result.displayName,city:result.city,district:result.district,state:result.division,zipCode:result.postalCode,country:result.country||'Bangladesh',coordinates:{lat:result.latitude,lng:result.longitude}})};
  const reverseAt=async(lat:number,lng:number)=>{onChange({...value,coordinates:{lat,lng}});setGeocoding(true);try{const result=await reverse({lat,lng}).unwrap();if(result.data)apply(result.data)}catch{setPendingMarker(null);toast.error('Address lookup failed. Coordinates were kept for manual editing.')}finally{setGeocoding(false)}};

  useEffect(()=>{const timer=setTimeout(()=>setDebounced(query.trim()),500);return()=>clearTimeout(timer)},[query]);
  useEffect(()=>{if(debounced.length>=3)search(debounced)},[debounced,search]);
  useEffect(()=>{if(!mapNode.current||map.current)return;const center:[number,number]=[value.coordinates.lat??fallback[0],value.coordinates.lng??fallback[1]];map.current=L.map(mapNode.current,{zoomControl:true}).setView(center,value.coordinates.lat?16:11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map.current);marker.current=L.marker(center,{draggable:true,icon:pin}).addTo(map.current);marker.current.on('dragend',()=>{const point=marker.current!.getLatLng();setPendingMarker({lat:point.lat,lng:point.lng})});setTimeout(()=>map.current?.invalidateSize(),100);return()=>{map.current?.remove();map.current=undefined}},[]);
  useEffect(()=>{const lat=value.coordinates.lat,lng=value.coordinates.lng;if(lat===undefined||lng===undefined||!map.current||!marker.current||pendingMarker)return;marker.current.setLatLng([lat,lng]);map.current.setView([lat,lng],16)},[value.coordinates.lat,value.coordinates.lng,pendingMarker]);

  const current=()=>{if(!navigator.geolocation)return toast.error('Geolocation is not supported. Please enter your address manually.');setLocating(true);navigator.geolocation.getCurrentPosition(async position=>{setAccuracy(position.coords.accuracy);await reverseAt(position.coords.latitude,position.coords.longitude);setLocating(false)},error=>{setLocating(false);setAccuracy(null);toast.error(error.code===error.PERMISSION_DENIED?'Location access was denied. Please enter your address manually.':'GPS location failed. Please enter your address manually.')},{enableHighAccuracy:true,timeout:12000,maximumAge:60000})};
  const select=(item:LocationResult)=>{apply(item);setQuery(item.displayName);setAccuracy(null)};
  const lat=value.coordinates.lat, lng=value.coordinates.lng;
  const copyCoordinates=async()=>{if(lat===undefined||lng===undefined)return toast.error('Select a location first');try{await navigator.clipboard.writeText(`${lat.toFixed(6)}, ${lng.toFixed(6)}`);toast.success('Coordinates copied')}catch{toast.error('Could not copy coordinates')}};
  const osmUrl=lat!==undefined&&lng!==undefined?`https://www.openstreetmap.org/?mlat=${lat}&mlon=${lng}#map=17/${lat}/${lng}`:'';

  return <div className="space-y-5">
    <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center"><button type="button" onClick={current} disabled={locating} className="btn btn-primary sm:w-auto"><Crosshair className="w-5 h-5 mr-2"/>{locating?'Finding location…':'Use My Current Location'}</button>{accuracy!==null&&<span className="px-3 py-2 rounded-xl bg-green-500/10 text-green-300 text-sm">Accuracy: ±{Math.round(accuracy)} meters</span>}{geocoding&&<span className="flex items-center gap-2 text-sm text-primary-300"><LoaderCircle className="w-4 h-4 animate-spin"/>Filling address…</span>}</div>
    <div className="relative"><Search className="absolute left-4 top-3.5 w-5 h-5 text-white/35 z-10"/><input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Search restaurant location" placeholder="Search by Area, Road, Landmark or City..." className="input pl-12" autoComplete="off"/>{(isFetching||geocoding)&&<LoaderCircle className="absolute right-4 top-3.5 w-5 h-5 animate-spin text-primary-400"/>}{debounced.length>=3&&data?.data&&<div className="absolute z-[1000] top-14 left-0 right-0 card overflow-hidden max-h-72 overflow-y-auto">{data.data.map((item,index)=><button type="button" key={`${item.latitude}-${item.longitude}-${index}`} onClick={()=>select(item)} className="w-full text-left p-3 flex gap-3 hover:bg-white/10 border-b border-white/5 focus:bg-white/10"><MapPin className="w-4 h-4 text-primary-400 shrink-0 mt-0.5"/><span className="text-sm">{item.displayName}</span></button>)}{!data.data.length&&<p className="p-4 text-sm text-white/40">No locations found.</p>}</div>}</div>
    <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{[['Restaurant Address','restaurantAddress'],['Area','area'],['City','city'],['District','district'],['Division / State','state'],['Postal Code','zipCode'],['Country','country']].map(([label,key])=><label key={key} className={key==='restaurantAddress'?'sm:col-span-2':''}><span className="text-sm text-white/60">{label}</span><input value={(value as any)[key]||''} onChange={e=>onChange({...value,[key]:e.target.value,...(key==='restaurantAddress'?{street:e.target.value}:{})})} className="input mt-2" required={['restaurantAddress','city','state','zipCode'].includes(key)}/></label>)}<label><span className="text-sm text-white/60">Latitude</span><input type="number" min="-90" max="90" step="any" value={lat??''} onChange={e=>onChange({...value,coordinates:{...value.coordinates,lat:e.target.value?Number(e.target.value):undefined}})} className="input mt-2"/></label><label><span className="text-sm text-white/60">Longitude</span><input type="number" min="-180" max="180" step="any" value={lng??''} onChange={e=>onChange({...value,coordinates:{...value.coordinates,lng:e.target.value?Number(e.target.value):undefined}})} className="input mt-2"/></label></div>

    <div className="rounded-2xl border border-primary-500/20 bg-gradient-to-br from-primary-500/10 to-white/[0.035] p-5"><div className="flex gap-3"><span className="w-10 h-10 rounded-xl bg-primary-500/20 text-primary-400 grid place-items-center"><MapPin className="w-5 h-5"/></span><div className="min-w-0 flex-1"><h3 className="font-bold">Current Restaurant Location</h3><dl className="grid sm:grid-cols-[100px_1fr] gap-x-3 gap-y-1 mt-3 text-sm"><dt className="text-white/40">Address:</dt><dd>{value.restaurantAddress||value.street||'Not selected'}</dd><dt className="text-white/40">Latitude:</dt><dd className="font-mono">{lat?.toFixed(6)??'—'}</dd><dt className="text-white/40">Longitude:</dt><dd className="font-mono">{lng?.toFixed(6)??'—'}</dd>{accuracy!==null&&<><dt className="text-white/40">GPS accuracy:</dt><dd>±{Math.round(accuracy)} meters</dd></>}</dl></div></div><div className="flex flex-wrap gap-2 mt-4"><button type="button" onClick={copyCoordinates} disabled={lat===undefined||lng===undefined} className="px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 disabled:opacity-40 text-sm flex items-center gap-2"><Copy className="w-4 h-4"/>Copy Coordinates</button><a href={osmUrl||undefined} target="_blank" rel="noopener noreferrer" aria-disabled={!osmUrl} className={`px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 text-sm flex items-center gap-2 ${!osmUrl?'pointer-events-none opacity-40':''}`}><ExternalLink className="w-4 h-4"/>Open in OpenStreetMap</a></div></div>

    <div className="relative"><div ref={mapNode} className="h-[360px] sm:h-[430px] rounded-2xl overflow-hidden border border-white/10 bg-white/5" aria-label="Interactive restaurant location map"/>{pendingMarker&&<div className="absolute z-[500] left-1/2 -translate-x-1/2 bottom-5 w-[calc(100%-2rem)] sm:w-auto rounded-2xl bg-dark-100/95 backdrop-blur-xl border border-primary-500/30 p-3 shadow-2xl"><p className="text-xs text-white/55 mb-2 text-center">Marker: {pendingMarker.lat.toFixed(6)}, {pendingMarker.lng.toFixed(6)}</p><button type="button" onClick={()=>reverseAt(pendingMarker.lat,pendingMarker.lng)} disabled={geocoding} className="btn btn-primary py-2 w-full"><MapPin className="w-4 h-4 mr-2"/>Use Marker Location</button></div>}</div>
    <button type="button" onClick={()=>mapNode.current?.requestFullscreen?.()} className="inline-flex items-center gap-2 text-sm text-primary-400 hover:text-primary-300"><Expand className="w-4 h-4"/>View map fullscreen</button><p className="text-xs text-white/35">Drag the marker, then choose “Use Marker Location” to update the address. Map data © OpenStreetMap contributors.</p>
  </div>;
};
export default RestaurantLocationPicker;
