import React, { useState } from 'react';
import { Banknote, CalendarDays, ChevronLeft, ChevronRight, CircleDollarSign, Download, FileSpreadsheet, Percent, Search, Wallet } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { useGetOwnerEarningsQuery, useLazyGetOwnerEarningsQuery, type EarningTransaction } from '../../store/api/restaurantFinanceApi';

const money = (value: number) => `৳${Math.round(value || 0).toLocaleString()}`;
const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[char]!));
const columns = ['Order ID','Customer','Food Total','Delivery Fee','Commission','Restaurant Earnings','Payment Method','Payment Status','Date'];
const rowValues = (row: EarningTransaction) => [row.orderNumber, row.customerName || 'Deleted customer', row.foodTotal.toFixed(2), row.deliveryFee.toFixed(2), row.commission.toFixed(2), row.restaurantEarnings.toFixed(2), row.paymentMethod, row.paymentStatus, new Date(row.date).toLocaleString()];

const RestaurantEarningsPage: React.FC = () => {
  const [search, setSearch] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const [sortOrder, setSortOrder] = useState('desc'); const [page, setPage] = useState(1);
  const { data, isLoading, isError } = useGetOwnerEarningsQuery({ page, limit: 12, search, from: from || undefined, to: to || undefined, sortOrder }, { pollingInterval: 30000, refetchOnFocus: true }); const earnings = data?.data;
  const [loadExport, { isFetching: isExporting }] = useLazyGetOwnerEarningsQuery();
  const report = async () => (await loadExport({ search, from: from || undefined, to: to || undefined, sortOrder, export: true }).unwrap()).data;
  const exportExcel = async () => { const full = await report(); if (!full?.transactions.length) return toast.error('No transactions to export'); const table = `<table><thead><tr>${columns.map(value => `<th>${value}</th>`).join('')}</tr></thead><tbody>${full.transactions.map(row => `<tr>${rowValues(row).map(value => `<td>${escapeHtml(value)}</td>`).join('')}</tr>`).join('')}</tbody></table>`; const blob = new Blob([`<html><body><h1>HalkaBite Earnings Report</h1>${table}</body></html>`], { type: 'application/vnd.ms-excel' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `HalkaBite-Earnings-${new Date().toISOString().slice(0,10)}.xls`; link.click(); URL.revokeObjectURL(link.href); };
  const exportPdf = async () => { const popup = window.open('', '_blank', 'width=1200,height=800'); if (!popup) return toast.error('Allow popups to export PDF'); const full = await report(); if (!full?.transactions.length) { popup.close(); return toast.error('No transactions to export'); } const rows = full.transactions.map(row => `<tr>${rowValues(row).map(value => `<td>${escapeHtml(value)}</td>`).join('')}</tr>`).join(''); popup.document.write(`<html><head><title>HalkaBite Earnings Report</title><style>@page{size:A4 landscape;margin:12mm}body{font:12px Arial;color:#111}h1{color:#ea580c}table{width:100%;border-collapse:collapse}th,td{padding:8px;border:1px solid #ddd;text-align:left}th{background:#f3f4f6}.summary{display:flex;gap:25px;margin:15px 0}</style></head><body><h1>HalkaBite Earnings Report</h1><p>Generated ${new Date().toLocaleString()}</p><div class="summary"><b>Total: ${money(full.summary.total)}</b><b>Commission: ${money(full.summary.totalCommission)}</b><b>Net: ${money(full.summary.netEarnings)}</b></div><table><thead><tr>${columns.map(value => `<th>${value}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>{window.print();}</script></body></html>`); popup.document.close(); };
  if (isLoading) return <div className="space-y-6 animate-pulse"><div className="h-16 rounded-2xl bg-white/5" /><div className="grid md:grid-cols-4 gap-4">{['today','week','month','total','commission','net','balance','trend'].map(slot => <div key={slot} className="h-32 rounded-2xl bg-white/5" />)}</div><div className="h-96 rounded-2xl bg-white/5" /></div>;
  if (isError || !earnings) return <div className="card p-12 text-center text-red-300">Earnings information could not be loaded.</div>;
  const cards = [
    ['Today’s Earnings', earnings.summary.today, CircleDollarSign, 'text-green-400 bg-green-500/15', earnings.summary.trends.today], ['Weekly Earnings', earnings.summary.weekly, CalendarDays, 'text-blue-400 bg-blue-500/15', earnings.summary.trends.weekly], ['Monthly Earnings', earnings.summary.monthly, Banknote, 'text-purple-400 bg-purple-500/15', earnings.summary.trends.monthly], ['Total Earnings', earnings.summary.total, Wallet, 'text-primary-400 bg-primary-500/15', undefined],
    ['Commission Paid', earnings.summary.totalCommission, Percent, 'text-red-400 bg-red-500/15'], ['Net Earnings', earnings.summary.netEarnings, Banknote, 'text-green-400 bg-green-500/15'], ['Withdrawable Balance', earnings.summary.withdrawableBalance, Wallet, 'text-yellow-400 bg-yellow-500/15'], ['Remaining Balance', earnings.summary.remainingBalance, Wallet, 'text-cyan-400 bg-cyan-500/15']
  ] as const;
  return <div className="space-y-7"><header className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><p className="text-primary-400 font-medium">Financial overview</p><h1 className="text-3xl font-bold mt-1">Earnings</h1><p className="text-white/50 mt-2">Completed and paid orders · {((earnings.commissionRate ?? 0) * 100).toFixed(0)}% platform commission</p></div><div className="flex gap-2"><button disabled={isExporting} onClick={exportPdf} className="btn btn-outline text-sm disabled:opacity-50"><Download className="w-4 h-4 mr-2" />PDF</button><button disabled={isExporting} onClick={exportExcel} className="btn bg-green-600 hover:bg-green-500 text-sm disabled:opacity-50"><FileSpreadsheet className="w-4 h-4 mr-2" />{isExporting ? 'Preparing…' : 'Excel'}</button></div></header>
    <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4">{cards.map(([label,value,Icon,color,trend]) => <div key={label} className="card card-hover p-5"><div className="flex justify-between"><span className={`w-11 h-11 rounded-xl grid place-items-center ${color}`}><Icon className="w-5 h-5" /></span>{trend !== undefined && <span className={`text-xs ${trend >= 0 ? 'text-green-400' : 'text-red-400'}`}>{trend >= 0 ? '↗' : '↘'} {Math.abs(trend).toFixed(1)}%</span>}</div><p className="text-2xl font-bold mt-5">{money(value)}</p><p className="text-sm text-white/45 mt-1">{label}</p></div>)}</section>
    <section className="card overflow-hidden"><div className="p-5 border-b border-white/10"><div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><h2 className="text-lg font-bold">Transaction History</h2><p className="text-xs text-white/40 mt-1">Every completed payment for your restaurant</p></div><div className="grid sm:grid-cols-2 lg:flex gap-2"><div className="relative"><Search className="absolute w-4 h-4 left-3 top-1/2 -translate-y-1/2 text-white/35" /><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Order or customer…" className="input pl-9 py-2" /></div><input type="date" value={from} onChange={e => { setFrom(e.target.value); setPage(1); }} className="input py-2" aria-label="From date" /><input type="date" value={to} onChange={e => { setTo(e.target.value); setPage(1); }} className="input py-2" aria-label="To date" /><button onClick={() => setSortOrder(value => value === 'desc' ? 'asc' : 'desc')} className="px-4 py-2 rounded-xl bg-white/5 text-sm whitespace-nowrap">{sortOrder === 'desc' ? 'Newest first' : 'Oldest first'}</button></div></div></div>
      <div className="overflow-x-auto"><table className="w-full min-w-[1120px]"><thead className="text-[11px] uppercase text-white/35 bg-white/[0.025]"><tr>{columns.map(column => <th key={column} className="text-left px-4 py-4">{column}</th>)}</tr></thead><tbody>{earnings.transactions.map(row => <tr key={row._id} className="border-t border-white/5 hover:bg-white/[0.025]"><td className="px-4 py-4 font-mono text-primary-300">#{row.orderNumber}</td><td className="px-4 py-4">{row.customerName || 'Deleted customer'}</td><td className="px-4 py-4">{money(row.foodTotal)}</td><td className="px-4 py-4">{money(row.deliveryFee)}</td><td className="px-4 py-4 text-red-300">−{money(row.commission)}</td><td className="px-4 py-4 font-bold text-green-400">{money(row.restaurantEarnings)}</td><td className="px-4 py-4 uppercase text-xs">{row.paymentMethod}</td><td className="px-4 py-4"><span className="badge badge-success capitalize">{row.paymentStatus}</span></td><td className="px-4 py-4 text-sm text-white/50">{new Date(row.date).toLocaleString()}</td></tr>)}</tbody></table>{!earnings.transactions.length && <div className="p-16 text-center"><CircleDollarSign className="w-14 h-14 mx-auto text-white/15" /><h3 className="font-bold text-lg mt-4">No completed payments</h3><p className="text-sm text-white/40 mt-2">Try changing the search or date filters.</p></div>}</div>
      {earnings.pagination.pages > 1 && <div className="p-4 border-t border-white/5 flex justify-center items-center gap-4"><button disabled={page === 1} onClick={() => setPage(value => value - 1)} className="p-2 rounded-lg bg-white/5 disabled:opacity-30"><ChevronLeft /></button><span className="text-sm text-white/45">Page {page} of {earnings.pagination.pages}</span><button disabled={page === earnings.pagination.pages} onClick={() => setPage(value => value + 1)} className="p-2 rounded-lg bg-white/5 disabled:opacity-30"><ChevronRight /></button></div>}
    </section>
  </div>;
};
export default RestaurantEarningsPage;
