import React, { useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, Box, ChevronLeft, ChevronRight, CircleDollarSign, Clock3, Package, Search, Star, TrendingUp, UtensilsCrossed } from 'lucide-react';
import { useGetOwnerAnalyticsQuery } from '../../store/api/restaurantFinanceApi';
import { BarChart, DonutChart, HorizontalBars } from '../../components/restaurant/AnalyticsCharts';

const money = (value: number) => `৳${Math.round(value || 0).toLocaleString()}`;
const foodPlaceholder = 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=200';
const Stat: React.FC<{ label: string; value: string | number; icon: React.ElementType; trend?: number; color?: string }> = ({ label, value, icon: Icon, trend, color = 'text-primary-400 bg-primary-500/15' }) => <div className="card p-5 card-hover"><div className="flex justify-between gap-3"><span className={`w-11 h-11 rounded-xl grid place-items-center ${color}`}><Icon className="w-5 h-5" /></span>{trend !== undefined && <span className={`text-xs flex items-center gap-1 ${trend >= 0 ? 'text-green-400' : 'text-red-400'}`}>{trend >= 0 ? <ArrowUpRight className="w-4 h-4" /> : <ArrowDownRight className="w-4 h-4" />}{Math.abs(trend).toFixed(1)}%</span>}</div><p className="text-2xl font-bold mt-5">{value}</p><p className="text-sm text-white/45 mt-1">{label}</p></div>;
const Skeleton = () => <div className="space-y-6 animate-pulse"><div className="h-16 bg-white/5 rounded-2xl" /><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{Array.from({ length: 8 }).map((_,i) => <div key={i} className="h-36 bg-white/5 rounded-2xl" />)}</div><div className="grid lg:grid-cols-2 gap-6"><div className="h-80 bg-white/5 rounded-2xl" /><div className="h-80 bg-white/5 rounded-2xl" /></div></div>;

const RestaurantAnalyticsPage: React.FC = () => {
  const [search, setSearch] = useState(''); const [sortBy, setSortBy] = useState('totalOrders'); const [sortOrder, setSortOrder] = useState('desc'); const [page, setPage] = useState(1);
  const { data, isLoading, isError } = useGetOwnerAnalyticsQuery({ page, limit: 10, search, sortBy, sortOrder }, { pollingInterval: 30000, refetchOnFocus: true }); const analytics = data?.data;
  const daily = useMemo(() => { if (!analytics) return []; const map = new Map(analytics.charts.dailySales.map(row => [row._id, row.revenue])); return Array.from({ length: 7 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - 6 + index); const key = date.toISOString().slice(0,10); return { label: date.toLocaleDateString(undefined, { weekday: 'short' }), value: map.get(key) || 0 }; }); }, [analytics]);
  const monthly = analytics?.charts.monthlyRevenue.map(row => ({ label: new Date(row._id.year, row._id.month - 1).toLocaleDateString(undefined, { month: 'short' }), value: row.revenue })) || [];
  if (isLoading) return <Skeleton />; if (isError || !analytics) return <div className="card p-12 text-center text-red-300">Analytics could not be loaded.</div>;
  const status = analytics.charts.orderStatus;
  return <div className="space-y-7"><header><p className="text-primary-400 font-medium">Live business intelligence</p><h1 className="text-3xl font-bold mt-1">Analytics</h1><p className="text-white/50 mt-2">Revenue, operations, menu performance, and customer sentiment calculated from your data.</p></header>
    <section><h2 className="text-sm font-semibold uppercase tracking-wider text-white/40 mb-3">Revenue Overview</h2><div className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><Stat label="Total Revenue" value={money(analytics.revenue.total)} icon={CircleDollarSign} /><Stat label="Today's Revenue" value={money(analytics.revenue.today)} icon={TrendingUp} trend={analytics.revenue.trends.today} /><Stat label="Weekly Revenue" value={money(analytics.revenue.weekly)} icon={TrendingUp} trend={analytics.revenue.trends.weekly} /><Stat label="Monthly Revenue" value={money(analytics.revenue.monthly)} icon={TrendingUp} trend={analytics.revenue.trends.monthly} /></div></section>
    <section><h2 className="text-sm font-semibold uppercase tracking-wider text-white/40 mb-3">Operations</h2><div className="grid grid-cols-2 md:grid-cols-4 xl:grid-cols-7 gap-3"><Stat label="Total Orders" value={analytics.orders.total} icon={Package} /><Stat label="Pending" value={analytics.orders.pending} icon={Clock3} color="text-yellow-400 bg-yellow-500/15" /><Stat label="Preparing" value={analytics.orders.preparing} icon={UtensilsCrossed} color="text-purple-400 bg-purple-500/15" /><Stat label="Picked Up" value={analytics.orders.picked_up} icon={Package} color="text-cyan-400 bg-cyan-500/15" /><Stat label="Delivered" value={analytics.orders.delivered} icon={Package} color="text-green-400 bg-green-500/15" /><Stat label="Cancelled" value={analytics.orders.cancelled} icon={Package} color="text-red-400 bg-red-500/15" /><Stat label="Menu Items" value={analytics.menu.total} icon={Box} /></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-3"><Stat label="Available Items" value={analytics.menu.available} icon={Box} color="text-green-400 bg-green-500/15" /><Stat label="Out of Stock" value={analytics.menu.outOfStock} icon={Box} color="text-red-400 bg-red-500/15" /><Stat label="Total Reviews" value={analytics.reviews.total} icon={Star} color="text-yellow-400 bg-yellow-500/15" /><Stat label="Average Rating" value={`${analytics.reviews.average.toFixed(1)}/5`} icon={Star} color="text-yellow-400 bg-yellow-500/15" /></div></section>
    <section className="grid md:grid-cols-3 gap-4">{([['bestSelling','Best Selling Food'],['mostReviewed','Most Reviewed Food'],['highestRated','Highest Rated Food']] as const).map(([key,label]) => { const food = analytics.highlights[key]; return <div key={key} className={`card p-4 flex gap-4 items-center ${food?.isDeleted ? 'opacity-70' : ''}`}>{food ? <><img src={food.image || foodPlaceholder} onError={event => { event.currentTarget.src = foodPlaceholder; }} alt="" className="w-16 h-16 rounded-xl object-cover" /><div className="min-w-0"><p className="text-xs text-primary-400 uppercase tracking-wide">{label}</p><h3 className="font-bold truncate mt-1">{food.name}</h3>{food.isDeleted && <span className="inline-block mt-1 px-2 py-0.5 rounded bg-red-500/15 text-red-300 text-[10px]">🗑 Deleted Menu Item</span>}<p className="text-xs text-white/45 mt-1">★ {food.rating.toFixed(1)} · {food.reviewCount} reviews</p></div></> : <p className="text-sm text-white/35">No {label.toLowerCase()} yet</p>}</div>; })}</section>
    <section className="grid xl:grid-cols-2 gap-6"><div className="card p-6"><h2 className="font-bold">Daily Sales</h2><p className="text-xs text-white/40">Last 7 days</p><BarChart data={daily} currency /></div><div className="card p-6"><h2 className="font-bold">Monthly Revenue</h2><p className="text-xs text-white/40">Last 12 months</p><BarChart data={monthly} color="#d946ef" currency /></div><div className="card p-6"><h2 className="font-bold">Order Status Distribution</h2><DonutChart values={[{ label:'Pending', value:status.pending || 0,color:'#eab308'},{label:'Preparing',value:status.preparing || 0,color:'#a855f7'},{label:'Delivery',value:status.out_for_delivery || 0,color:'#06b6d4'},{label:'Delivered',value:status.delivered || 0,color:'#22c55e'},{label:'Cancelled',value:status.cancelled || 0,color:'#ef4444'}]} /></div><div className="card p-6"><h2 className="font-bold">Top 5 Best Selling Foods</h2><HorizontalBars data={analytics.charts.topSelling} /></div><div className="card p-6 xl:col-span-2"><h2 className="font-bold">Top 5 Highest Rated Foods</h2><HorizontalBars data={analytics.charts.topRated} suffix="★" /></div></section>
    <section className="card overflow-hidden"><div className="p-5 border-b border-white/10 flex flex-col md:flex-row justify-between gap-3"><div><h2 className="font-bold text-lg">Food Performance</h2><p className="text-xs text-white/40">Current and historical menu performance</p></div><div className="flex flex-col sm:flex-row gap-2"><div className="relative"><Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-white/35" /><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search food…" className="input pl-9 py-2" /></div><select value={sortBy} onChange={e => { setSortBy(e.target.value); setPage(1); }} className="input py-2"><option value="totalOrders">Orders</option><option value="totalRevenue">Revenue</option><option value="rating">Rating</option><option value="reviewCount">Reviews</option><option value="name">Name</option></select><button onClick={() => setSortOrder(value => value === 'desc' ? 'asc' : 'desc')} className="px-4 rounded-xl bg-white/5 text-sm">{sortOrder === 'desc' ? 'Descending' : 'Ascending'}</button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px]"><thead className="text-xs uppercase text-white/35 bg-white/[0.025]"><tr>{['Food','Total Orders','Total Revenue','Average Rating','Total Reviews'].map(title => <th key={title} className="text-left px-5 py-4">{title}</th>)}</tr></thead><tbody>{analytics.foodPerformance.rows.map(food => <tr key={food._id} className={`border-t border-white/5 hover:bg-white/[0.025] ${food.isDeleted ? 'opacity-60' : ''}`}><td className="px-5 py-4"><div className="flex items-center gap-3"><img src={food.image || foodPlaceholder} onError={event => { event.currentTarget.src = foodPlaceholder; }} alt="" className="w-11 h-11 rounded-lg object-cover" /><div><b>{food.name}</b>{food.isDeleted && <span className="block mt-1 text-[10px] text-red-300">🗑 Deleted Menu Item</span>}</div></div></td><td className="px-5 py-4">{food.totalOrders}</td><td className="px-5 py-4 font-semibold text-green-400">{money(food.totalRevenue)}</td><td className="px-5 py-4 text-yellow-400">★ {food.rating.toFixed(1)}</td><td className="px-5 py-4">{food.reviewCount}</td></tr>)}</tbody></table>{!analytics.foodPerformance.rows.length && <div className="p-12 text-center text-white/35">No food performance data found.</div>}</div>{analytics.foodPerformance.pagination.pages > 1 && <div className="p-4 border-t border-white/5 flex justify-center items-center gap-4"><button disabled={page === 1} onClick={() => setPage(value => value - 1)} className="p-2 bg-white/5 rounded-lg disabled:opacity-30"><ChevronLeft /></button><span className="text-sm text-white/45">Page {page} of {analytics.foodPerformance.pagination.pages}</span><button disabled={page === analytics.foodPerformance.pagination.pages} onClick={() => setPage(value => value + 1)} className="p-2 bg-white/5 rounded-lg disabled:opacity-30"><ChevronRight /></button></div>}</section>
  </div>;
};
export default RestaurantAnalyticsPage;
