import { Response } from 'express';
import { Types } from 'mongoose';
import { AuthRequest } from '../middleware/auth';
import { CustomerNotification } from '../models';
import notificationEmitter,{customerOrderNotificationChannel}from'../services/customerOrderNotificationService';
import { openSseStream } from '../utils/sse';

const orderFilter=(user:any)=>({user,orderId:{$exists:true},type:{$exists:true}});
export const listCustomerOrderNotifications=async(req:AuthRequest,res:Response)=>{const page=Math.max(Number(req.query.page)||1,1),limit=Math.min(Math.max(Number(req.query.limit)||20,1),50),filter=orderFilter(req.user._id);const[notifications,total,unreadCount]=await Promise.all([CustomerNotification.find(filter).populate('restaurantId','name image').populate('orderId','orderNumber orderStatus deliveryStatus').sort({isRead:1,createdAt:-1}).skip((page-1)*limit).limit(limit).lean(),CustomerNotification.countDocuments(filter),CustomerNotification.countDocuments({...filter,isRead:false})]);res.json({success:true,data:{notifications,unreadCount,pagination:{page,limit,total,pages:Math.ceil(total/limit)}}});};
export const readCustomerOrderNotification=async(req:AuthRequest,res:Response)=>{const row=await CustomerNotification.findOneAndUpdate({_id:req.params.id,...orderFilter(req.user._id)},{isRead:true},{new:true});if(!row)return res.status(404).json({success:false,message:'Notification not found'});res.json({success:true,data:row});};
export const readDisplayedCustomerOrderNotifications=async(req:AuthRequest,res:Response)=>{const rawIds:unknown[]=Array.isArray(req.body.ids)?req.body.ids:[];const validIds=new Map<string,Types.ObjectId>();for(const rawId of rawIds){if(typeof rawId!=='string'||!Types.ObjectId.isValid(rawId))continue;const objectId=new Types.ObjectId(rawId);validIds.set(objectId.toHexString(),objectId);if(validIds.size===50)break}const ids:Types.ObjectId[]=Array.from(validIds.values());if(!ids.length)return res.status(400).json({success:false,message:'Notification IDs are required'});const result=await CustomerNotification.updateMany({_id:{$in:ids},...orderFilter(req.user._id),isRead:false},{$set:{isRead:true}});const unreadCount=await CustomerNotification.countDocuments({...orderFilter(req.user._id),isRead:false});res.json({success:true,data:{updatedCount:result.modifiedCount,unreadCount}});};
export const deleteCustomerOrderNotification=async(req:AuthRequest,res:Response)=>{const row=await CustomerNotification.findOneAndDelete({_id:req.params.id,...orderFilter(req.user._id)});if(!row)return res.status(404).json({success:false,message:'Notification not found'});res.json({success:true});};
export const deleteAllReadCustomerOrderNotifications=async(req:AuthRequest,res:Response)=>{const result=await CustomerNotification.deleteMany({...orderFilter(req.user._id),isRead:true});res.json({success:true,data:{deletedCount:result.deletedCount}});};
export const streamCustomerOrderNotifications=async(req:AuthRequest,res:Response)=>{const stream=openSseStream(req,res),channel=customerOrderNotificationChannel(req.user._id.toString()),send=(data:any)=>stream.send(data);notificationEmitter.on(channel,send);stream.send({type:'connected'});stream.onClose(()=>notificationEmitter.off(channel,send));};
