import React, { useMemo, useState } from 'react';
import { CircleDollarSign, CreditCard, Plus, ReceiptText, TrendingUp, Wallet, X } from 'lucide-react';
import toast from 'react-hot-toast';
import { BarChart } from '../restaurant/AnalyticsCharts';
import { useGetRestaurantCommissionAnalyticsQuery, useGetRestaurantCommissionOrdersQuery, useGetRestaurantCommissionPaymentsQuery, useGetRestaurantCommissionSummaryQuery, useRecordRestaurantCommissionPaymentMutation, type CommissionPaymentMethod } from '../../store/api/adminApi';

const money=(value=0)=>`৳${value.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const today=()=>new Date().toISOString().slice(0,10);
const initialPayment={amount:'',paymentMethod:'cash' as CommissionPaymentMethod,referenceId:'',paymentDate:today(),notes:''};
const Card:React.FC<{label:string;value:string|number;tone?:string;icon:React.ReactNode}>=({label,value,tone='text-white',icon})=><div className="card p-5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/5 text-primary-400">{icon}</span><p className="mt-4 text-sm text-white/45">{label}</p><b className={`mt-1 block text-2xl ${tone}`}>{value}</b></div>;

const RestaurantCommissionPanel:React.FC<{restaurantId:string;view:'commission'|'payments'}>=({restaurantId,view})=>{
 const[page,setPage]=useState(1);const[from,setFrom]=useState('');const[to,setTo]=useState('');const[status,setStatus]=useState('all');const[method,setMethod]=useState('all');const[dialog,setDialog]=useState(false);const[form,setForm]=useState(initialPayment);
 const{data:summaryData,isLoading:summaryLoading}=useGetRestaurantCommissionSummaryQuery(restaurantId);
 const{data:ordersData,isLoading:ordersLoading}=useGetRestaurantCommissionOrdersQuery({restaurantId,page,limit:20,status,from:from||undefined,to:to||undefined},{skip:view!=='commission'});
 const{data:paymentsData,isLoading:paymentsLoading}=useGetRestaurantCommissionPaymentsQuery({restaurantId,page,limit:20,status,method,from:from||undefined,to:to||undefined},{skip:view!=='payments'});
 const{data:analyticsData}=useGetRestaurantCommissionAnalyticsQuery({restaurantId,from:from||undefined,to:to||undefined});
 const[record,{isLoading:recording}]=useRecordRestaurantCommissionPaymentMutation();const summary=summaryData?.data;const analytics=analyticsData?.data;
 const pagination=view==='commission'?ordersData?.data?.pagination:paymentsData?.data?.pagination;
 const months=useMemo(()=>analytics?.monthly.map(row=>({label:`${row.month}/${String(row.year).slice(-2)}`,value:row.commission}))||[],[analytics]);
 const preset=(kind:string)=>{const now=new Date(),start=new Date(now),end=new Date(now);if(kind==='today'){}else if(kind==='yesterday'){start.setDate(start.getDate()-1);end.setDate(end.getDate()-1)}else if(kind==='7days')start.setDate(start.getDate()-6);else if(kind==='month')start.setDate(1);else if(kind==='lastmonth'){start.setMonth(start.getMonth()-1,1);end.setDate(0)}setFrom(start.toISOString().slice(0,10));setTo(end.toISOString().slice(0,10));setPage(1)};
 const submit=async(event:React.FormEvent)=>{event.preventDefault();if(!summary)return;const amount=Number(form.amount);if(!Number.isFinite(amount)||amount<=0)return toast.error('Enter a valid payment amount');if(amount>summary.commissionDue+0.009)return toast.error('Payment amount cannot exceed the current commission due.');if(form.paymentMethod!=='cash'&&!form.referenceId.trim())return toast.error('Reference ID is required');try{await record({restaurantId,amount,paymentMethod:form.paymentMethod,referenceId:form.referenceId.trim()||undefined,paymentDate:form.paymentDate,notes:form.notes.trim()||undefined}).unwrap();setDialog(false);setForm(initialPayment);toast.success('Commission payment recorded')}catch(error:unknown){const value=error as{data?:{message?:string}};toast.error(value.data?.message||'Unable to record payment')}};
 if(summaryLoading)return <div className="grid gap-4 md:grid-cols-3">{Array.from({length:6}).map((_,i)=><div key={i} className="h-32 animate-pulse rounded-2xl bg-white/5"/>)}</div>;
 if(!summary)return <div className="card p-12 text-center text-red-300">Commission information is unavailable.</div>;
 return <div className="space-y-6">
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><Card label="Total Order Value" value={money(summary.totalOrderValue)} icon={<TrendingUp/>}/><Card label="Eligible Restaurant Sales" value={money(summary.eligibleSales)} icon={<ReceiptText/>}/><Card label="Total Commission" value={money(summary.totalCommission)} tone="text-primary-300" icon={<CircleDollarSign/>}/><Card label="Commission Paid" value={money(summary.commissionPaid)} tone="text-green-400" icon={<CreditCard/>}/><Card label="Commission Due" value={money(summary.commissionDue)} tone={summary.commissionDue?'text-yellow-300':'text-green-400'} icon={<Wallet/>}/><Card label="Restaurant Earnings" value={money(summary.restaurantEarnings)} icon={<TrendingUp/>}/></div>
  <section className="card flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="text-sm text-white/45">Current Commission Configuration</p><b className="text-xl capitalize">{summary.currentCommission.mode==='none'?'No commission':summary.currentCommission.mode==='percentage'?`${summary.currentCommission.value}% per eligible order`:`${money(summary.currentCommission.value)} per eligible order`}</b><small className="ml-3 rounded-full bg-white/5 px-2 py-1 capitalize text-white/40">{summary.currentCommission.scope}</small></div><button onClick={()=>setDialog(true)} disabled={summary.commissionDue<=0} className="btn btn-primary disabled:opacity-40"><Plus className="mr-2 h-4 w-4"/>Record Commission Payment</button></section>
  <section className="card p-5"><div className="flex flex-wrap items-end gap-3"><label><span className="text-xs text-white/45">From</span><input type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}} className="input mt-1 block"/></label><label><span className="text-xs text-white/45">To</span><input type="date" value={to} min={from||undefined} onChange={e=>{setTo(e.target.value);setPage(1)}} className="input mt-1 block"/></label><div className="flex flex-wrap gap-2">{[['today','Today'],['yesterday','Yesterday'],['7days','Last 7 Days'],['month','This Month'],['lastmonth','Last Month']].map(([key,label])=><button key={key} onClick={()=>preset(key)} className="rounded-lg bg-white/5 px-3 py-2 text-xs hover:bg-white/10">{label}</button>)}</div><button onClick={()=>{setFrom('');setTo('');setStatus('all');setMethod('all');setPage(1)}} className="text-sm text-red-300">Clear filters</button></div></section>
  {view==='commission'?<>
   <div className="grid gap-6 xl:grid-cols-3"><section className="card p-5 xl:col-span-2"><h2 className="text-xl font-bold">Commission Generated Over Time</h2><BarChart currency data={months}/></section><section className="card p-5"><h2 className="text-xl font-bold">Paid vs Due</h2><div className="mt-8 space-y-6">{[['Paid',summary.commissionPaid,'bg-green-500'],['Due',summary.commissionDue,'bg-yellow-500']].map(([label,value,color])=><div key={String(label)}><div className="mb-2 flex justify-between text-sm"><span>{label}</span><b>{money(Number(value))}</b></div><div className="h-4 overflow-hidden rounded-full bg-white/10"><div className={`h-full ${color}`} style={{width:`${summary.totalCommission?Number(value)/summary.totalCommission*100:0}%`}}/></div></div>)}</div></section><section className="card p-5 xl:col-span-3"><h2 className="text-xl font-bold">Restaurant Sales vs Commission</h2><div className="mt-6 grid gap-5 md:grid-cols-3">{[['Eligible Sales',summary.eligibleSales,'bg-blue-500'],['Commission',summary.totalCommission,'bg-primary-500'],['Restaurant Earnings',summary.restaurantEarnings,'bg-green-500']].map(([label,value,color])=><div key={String(label)}><div className="mb-2 flex justify-between text-sm"><span>{label}</span><b>{money(Number(value))}</b></div><div className="h-3 overflow-hidden rounded-full bg-white/10"><div className={`h-full ${color}`} style={{width:`${summary.eligibleSales?Number(value)/summary.eligibleSales*100:0}%`}}/></div></div>)}</div></section></div>
   <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-white/5 p-5"><h2 className="text-xl font-bold">Order-level Commission</h2><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="input w-auto"><option value="all">All statuses</option><option value="paid">Paid</option><option value="partial">Partial</option><option value="pending">Pending</option></select></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-white/[.03] text-white/40"><tr>{['Order','Customer','Date','Order Total','Eligible Sales','Commission Rule','Commission','Restaurant Earnings','Status'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{ordersData?.data?.orders.map(row=><tr key={row._id} className="border-t border-white/5"><td className="px-4 py-4 font-mono">#{row.orderNumber}</td><td className="px-4 py-4">{row.customer?.name||'Deleted customer'}</td><td className="px-4 py-4">{new Date(row.orderDate).toLocaleString()}</td><td className="px-4 py-4">{money(row.orderTotal)}</td><td className="px-4 py-4">{money(row.eligibleSales)}</td><td className="px-4 py-4 capitalize">{row.commissionMode==='percentage'?`${row.commissionValue}%`:row.commissionMode==='fixed'?money(row.commissionValue):'None'}</td><td className="px-4 py-4 font-bold text-primary-300">{money(row.commissionAmount)}</td><td className="px-4 py-4">{money(row.restaurantEarnings)}</td><td className="px-4 py-4"><span className={`rounded-full px-2 py-1 text-xs capitalize ${row.commissionPaymentStatus==='paid'?'bg-green-500/10 text-green-300':row.commissionPaymentStatus==='partial'?'bg-blue-500/10 text-blue-300':'bg-yellow-500/10 text-yellow-300'}`}>{row.commissionPaymentStatus}</span></td></tr>)}</tbody></table>{ordersLoading&&<p className="p-10 text-center text-white/40">Loading commission orders…</p>}{!ordersLoading&&!ordersData?.data?.orders.length&&<p className="p-12 text-center text-white/40">No eligible commission orders found.</p>}</div></section>
  </>:<section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-white/5 p-5"><h2 className="text-xl font-bold">Commission Payment History</h2><div className="flex gap-2"><select value={method} onChange={e=>{setMethod(e.target.value);setPage(1)}} className="input w-auto"><option value="all">All methods</option>{['cash','bkash','nagad','rocket','bank_transfer','other'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="input w-auto"><option value="all">All statuses</option><option value="verified">Verified</option></select></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-white/[.03] text-white/40"><tr>{['Payment ID','Date','Previous Due','Paid','Remaining Due','Method','Reference','Status','Created By','Notes'].map(x=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{paymentsData?.data?.payments.map(row=><tr key={row._id} className="border-t border-white/5"><td className="px-4 py-4 font-mono text-primary-300">{row.paymentId}</td><td className="px-4 py-4">{new Date(row.paymentDate).toLocaleString()}</td><td className="px-4 py-4">{money(row.previousDue)}</td><td className="px-4 py-4 font-bold text-green-400">{money(row.amount)}</td><td className="px-4 py-4">{money(row.remainingDue)}</td><td className="px-4 py-4 capitalize">{row.paymentMethod.replace('_',' ')}</td><td className="px-4 py-4 font-mono">{row.referenceId||'—'}</td><td className="px-4 py-4"><span className="rounded-full bg-green-500/10 px-2 py-1 text-xs text-green-300">Verified</span></td><td className="px-4 py-4">{row.createdBy?.name||'Admin'}</td><td className="max-w-56 truncate px-4 py-4 text-white/45">{row.notes||'—'}</td></tr>)}</tbody></table>{paymentsLoading&&<p className="p-10 text-center text-white/40">Loading payments…</p>}{!paymentsLoading&&!paymentsData?.data?.payments.length&&<p className="p-12 text-center text-white/40">No commission payments recorded.</p>}</div></section>}
  {pagination&&pagination.pages>1&&<div className="flex justify-center gap-3"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)} className="btn btn-ghost">Previous</button><span className="py-3 text-sm">Page {page} of {pagination.pages}</span><button disabled={page>=pagination.pages} onClick={()=>setPage(p=>p+1)} className="btn btn-ghost">Next</button></div>}
  {dialog&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/75 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><form onSubmit={submit} className="card w-full max-w-lg p-6"><div className="flex justify-between"><div><p className="text-sm text-primary-300">{summary.restaurant.name}</p><h2 className="text-2xl font-bold">Record Commission Payment</h2><p className="mt-1 text-sm text-white/45">Current due: {money(summary.commissionDue)}</p></div><button type="button" onClick={()=>setDialog(false)} aria-label="Close"><X/></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label><span className="text-sm text-white/55">Amount</span><input required type="number" min="0.01" max={summary.commissionDue} step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} className="input mt-2 w-full"/></label><label><span className="text-sm text-white/55">Payment Method</span><select value={form.paymentMethod} onChange={e=>setForm({...form,paymentMethod:e.target.value as CommissionPaymentMethod})} className="input mt-2 w-full">{['cash','bkash','nagad','rocket','bank_transfer','other'].map(x=><option key={x} value={x}>{x.replace('_',' ')}</option>)}</select></label><label><span className="text-sm text-white/55">Reference ID</span><input required={form.paymentMethod!=='cash'} maxLength={100} value={form.referenceId} onChange={e=>setForm({...form,referenceId:e.target.value})} className="input mt-2 w-full"/></label><label><span className="text-sm text-white/55">Payment Date</span><input required type="date" max={today()} value={form.paymentDate} onChange={e=>setForm({...form,paymentDate:e.target.value})} className="input mt-2 w-full"/></label><label className="sm:col-span-2"><span className="text-sm text-white/55">Notes</span><textarea maxLength={1000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} className="input mt-2 min-h-24 w-full"/></label></div><div className="mt-6 flex gap-3"><button type="button" onClick={()=>setDialog(false)} className="btn btn-outline flex-1 justify-center">Cancel</button><button disabled={recording} className="btn btn-primary flex-1 justify-center">{recording?'Recording…':'Record Payment'}</button></div></form></div>}
 </div>;
};
export default RestaurantCommissionPanel;
