import React,{useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,Check,CheckCheck,ImagePlus,MessageCircle,Package,Reply,Search,Send,ShieldOff,Smile}from'lucide-react';
import{toast}from'react-hot-toast';
import{Link,useSearchParams}from'react-router-dom';
import{useAppSelector}from'../store/hooks';
import{type ChatMessage,type Conversation,useGetConversationsQuery,useLazyGetMessagesQuery,useMarkChatReadMutation,useSendChatMessageMutation,useSendTypingMutation,useSetChatBlockedMutation,useStartConversationMutation}from'../store/api/chatApi';
import{useUploadImageMutation}from'../store/api/uploadApi';
import{uniqueById}from'../utils/uniqueById';
import{parseEventData}from'../utils/realtime';

const emojis=['😀','😂','😍','👍','🙏','🎉','🍔','❤️'];
const relative=(date:string)=>{const seconds=Math.floor((Date.now()-new Date(date).getTime())/1000);if(seconds<60)return'just now';if(seconds<3600)return`${Math.floor(seconds/60)}m ago`;if(seconds<86400)return`${Math.floor(seconds/3600)}h ago`;return new Date(date).toLocaleDateString()};
const statusMeta=(status:string)=>({pending:['🟡','Pending','bg-yellow-500/15 text-yellow-300'],confirmed:['🔵','Accepted','bg-blue-500/15 text-blue-300'],preparing:['🟣','Preparing','bg-purple-500/15 text-purple-300'],ready:['🟠','Ready for Pickup','bg-orange-500/15 text-orange-300'],picked_up:['🚚','Picked Up','bg-cyan-500/15 text-cyan-300'],out_for_delivery:['🟢','Out for Delivery','bg-green-500/15 text-green-300'],delivered:['✅','Delivered','bg-emerald-500/15 text-emerald-300'],cancelled:['❌','Cancelled','bg-red-500/15 text-red-300']}[status]||['📦',status.replaceAll('_',' '),'bg-white/10 text-white/70']);
const MessagingPage:React.FC<{restaurantMode?:boolean}>=({restaurantMode=false})=>{
 const user=useAppSelector(s=>s.auth.user);const[params]=useSearchParams();const{data,refetch,isLoading}=useGetConversationsQuery();const[start]=useStartConversationMutation();const[getMessages]=useLazyGetMessagesQuery();const[send,{isLoading:sending}]=useSendChatMessageMutation();const[markRead]=useMarkChatReadMutation();const[block]=useSetChatBlockedMutation();const[typing]=useSendTypingMutation();const[upload,{isLoading:uploading}]=useUploadImageMutation();
 const[selected,setSelected]=useState<string>();const[messages,setMessages]=useState<ChatMessage[]>([]);const[hasMore,setHasMore]=useState(false);const[cursor,setCursor]=useState<string>();const[text,setText]=useState('');const[reply,setReply]=useState<ChatMessage>();const[search,setSearch]=useState('');const[emoji,setEmoji]=useState(false);const[otherTyping,setOtherTyping]=useState(false);const[liveStatuses,setLiveStatuses]=useState<Record<string,string>>({});const bottom=useRef<HTMLDivElement>(null);const typingTimer=useRef<number|undefined>(undefined);
 const conversations=useMemo(()=>uniqueById(data?.data||[]),[data]);const current=conversations.find(c=>c._id===selected);const unread=(c:Conversation)=>restaurantMode?c.restaurantUnread:c.customerUnread;
 const filtered=useMemo(()=>conversations.filter(c=>`${c.customerId.name} ${c.orderId.orderNumber} ${c.restaurantId.name}`.toLowerCase().includes(search.toLowerCase())),[conversations,search]);
 useEffect(()=>{const restaurantId=params.get('restaurantId'),orderId=params.get('orderId');if((restaurantMode&&orderId)||(!restaurantMode&&restaurantId))start({restaurantId:restaurantId||undefined,orderId:orderId||undefined}).unwrap().then((r:any)=>{setSelected(r.data._id);refetch()}).catch((e:any)=>toast.error(e?.data?.message||'Unable to open chat'))},[params,restaurantMode,start,refetch]);
 useEffect(()=>{if(!selected)return;getMessages({id:selected}).unwrap().then(r=>{setMessages(uniqueById(r.data.messages));setHasMore(r.data.hasMore);setCursor(r.data.nextCursor);markRead(selected);setTimeout(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),20)})},[selected,getMessages,markRead]);
 useEffect(()=>{if(!user)return;const base=(import.meta.env.VITE_API_URL||'http://localhost:5000/api').replace(/\/$/,'');const events=new EventSource(`${base}/chat/events`,{withCredentials:true});events.onmessage=e=>{const event=parseEventData<any>(e);if(!event)return;if(event.type==='message'&&event.conversationId===selected){setMessages(old=>old.some(m=>m._id===event.message._id)?old:[...old,event.message]);markRead(selected!);setTimeout(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),20)}if(event.type==='read'&&event.conversationId===selected)setMessages(old=>old.map(m=>m.senderRole!==event.readerRole?{...m,isRead:true,readAt:event.readAt}:m));if(event.type==='block')toast(event.blocked?'Messaging has been blocked':'Messaging has been unblocked',{icon:'🔒'});if(event.type==='typing'&&event.conversationId===selected&&event.senderRole!==(restaurantMode?'restaurant':'user'))setOtherTyping(event.isTyping)};return()=>events.close()},[user,selected,restaurantMode,markRead]);
 useEffect(()=>{if(!user)return;const base=(import.meta.env.VITE_API_URL||'http://localhost:5000/api').replace(/\/$/,'');const events=new EventSource(`${base}/orders/events/stream`,{withCredentials:true});const update=(message:Event)=>{const event=parseEventData<any>(message as MessageEvent<string>);if(event?.orderId&&event.status)setLiveStatuses(old=>({...old,[event.orderId]:event.status}))};events.addEventListener('order-lifecycle',update);return()=>{events.removeEventListener('order-lifecycle',update);events.close()}},[user]);
 const submit=async()=>{if(!current||(!text.trim()))return;try{const r=await send({id:current._id,message:text.trim(),replyTo:reply?._id}).unwrap();setMessages(old=>old.some(m=>m._id===r.data._id)?old:[...old,r.data]);setText('');setReply(undefined);typing({id:current._id,isTyping:false});setTimeout(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),20)}catch(e:any){toast.error(e?.data?.message||'Message failed')}};
 const type=(value:string)=>{setText(value);if(!current)return;typing({id:current._id,isTyping:true});window.clearTimeout(typingTimer.current);typingTimer.current=window.setTimeout(()=>typing({id:current._id,isTyping:false}),1200)};
 const image=async(file?:File)=>{if(!file||!current)return;const form=new FormData();form.append('image',file);try{const uploaded=await upload(form).unwrap();const r=await send({id:current._id,imageUrl:uploaded.filePath,message:text.trim()||undefined,replyTo:reply?._id}).unwrap();setMessages(old=>uniqueById([...old,r.data]));setText('');setReply(undefined);setTimeout(()=>bottom.current?.scrollIntoView({behavior:'smooth'}),20)}catch(e:any){toast.error(e?.data?.message||'Image failed')}};
 const more=async()=>{if(!selected||!cursor)return;const pane=bottom.current?.parentElement;const previousHeight=pane?.scrollHeight||0;const previousTop=pane?.scrollTop||0;const r=await getMessages({id:selected,before:cursor}).unwrap();setMessages(old=>uniqueById([...r.data.messages,...old]));setHasMore(r.data.hasMore);setCursor(r.data.nextCursor);requestAnimationFrame(()=>{if(pane)pane.scrollTop=previousTop+(pane.scrollHeight-previousHeight)})};
 const toggleBlock=async()=>{if(!current)return;const next=!current.isBlocked;if(next&&!confirm('Are you sure you want to block this customer?'))return;try{await block({id:current._id,blocked:next}).unwrap()}catch(e:any){toast.error(e?.data?.message||'Action failed')}};
 let lastDay='';return <div className="chat-shell h-[calc(100vh-8rem)] min-h-[560px] card overflow-hidden grid md:grid-cols-[320px_1fr]">
  <aside className={`${selected?'hidden md:flex':'flex'} flex-col border-r border-white/10 min-w-0`}><div className="p-4 border-b border-white/10"><h1 className="text-xl font-bold flex gap-2"><MessageCircle className="text-primary-400"/>{restaurantMode?'Customer Chats':'Restaurant Chats'}</h1><label className="relative block mt-4"><Search className="absolute left-3 top-2.5 w-4 text-white/40"/><input className="input pl-9 py-2" placeholder="Search customer or order ID" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="overflow-y-auto flex-1">{isLoading?<div className="p-5 animate-pulse text-white/40">Loading conversations…</div>:!filtered.length?<div className="p-8 text-center text-white/40"><MessageCircle className="mx-auto mb-3"/>No conversations yet</div>:filtered.map(c=>{const party=restaurantMode?c.customerId:c.restaurantId;const meta=statusMeta(liveStatuses[c.orderId._id]||c.orderId.deliveryStatus||c.orderId.orderStatus);return <button key={c._id} onClick={()=>setSelected(c._id)} className={`w-full p-4 flex gap-3 text-left border-b border-white/5 hover:bg-white/5 ${selected===c._id?'bg-primary-500/10':''}`}><img src={party.avatar||party.image||`https://ui-avatars.com/api/?name=${encodeURIComponent(party.name)}`} className="w-11 h-11 rounded-full object-cover"/><span className="min-w-0 flex-1"><span className="flex justify-between gap-2"><b className="truncate">{party.name}</b><small className="text-white/35 shrink-0">{c.lastMessageAt?relative(c.lastMessageAt):''}</small></span><span className="block text-xs text-white/50 truncate">“{c.lastMessage||'Start the conversation'}”</span><span className="flex items-center gap-2 mt-1"><small className="text-primary-300">📦 {c.orderId.orderNumber}</small><small className={`px-1.5 py-0.5 rounded-full capitalize ${meta[2]}`}>{meta[0]} {meta[1]}</small></span></span>{unread(c)>0&&<i className="not-italic text-xs bg-red-500 rounded-full min-w-5 h-5 px-1 grid place-items-center">{unread(c)}</i>}</button>})}</div></aside>
  {!current?<main className="hidden md:grid place-items-center text-center text-white/40"><div><MessageCircle className="w-14 h-14 mx-auto mb-3"/><p>Select a conversation</p></div></main>:<main className="flex flex-col min-w-0 min-h-0 overflow-hidden"><header className="shrink-0 p-3 sm:p-4 border-b border-white/10 flex items-center gap-3"><button onClick={()=>setSelected(undefined)} className="md:hidden"><ArrowLeft/></button><img src={(restaurantMode?current.customerId.avatar:current.restaurantId.image)||`https://ui-avatars.com/api/?name=${encodeURIComponent(restaurantMode?current.customerId.name:current.restaurantId.name)}`} className="w-10 h-10 rounded-full object-cover"/><div className="min-w-0 flex-1"><b className="block truncate">{restaurantMode?current.customerId.name:current.restaurantId.name}</b><p className="text-xs text-white/45">{restaurantMode&&<>Customer ID: {current.customerId._id} · </>}<Link to={`${restaurantMode?'/restaurant-dashboard/orders':'/orders'}?order=${current.orderId._id}`} aria-label={`Open order ${current.orderId.orderNumber}`} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-primary-500/10 text-primary-300 hover:bg-primary-500/20 hover:underline focus:outline-none focus:ring-2 focus:ring-primary-400 transition"><Package className="w-3"/>Order #{current.orderId.orderNumber}</Link> · <span className="capitalize">{current.orderId.orderStatus.replaceAll('_',' ')}</span> · {relative(current.orderId.createdAt)}</p></div>{restaurantMode&&<button onClick={toggleBlock} className={`btn text-xs ${current.isBlocked?'bg-green-600':'bg-red-500/15 text-red-300'}`}><ShieldOff className="w-4 mr-1"/>{current.isBlocked?'Unblock':'Block'}</button>}</header>
  {(()=>{const meta=statusMeta(liveStatuses[current.orderId._id]||current.orderId.deliveryStatus||current.orderId.orderStatus);return <div className="shrink-0 px-3 sm:px-4 py-3 bg-primary-500/5 border-b border-white/5 grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-2 text-xs"><Link to={`${restaurantMode?'/restaurant-dashboard/orders':'/orders'}?order=${current.orderId._id}`} aria-label={`Open order ${current.orderId.orderNumber}`} className="font-semibold text-primary-300 hover:underline focus:outline-none focus:ring-2 focus:ring-primary-400 rounded">📦 #{current.orderId.orderNumber}</Link><span className={`justify-self-start px-2 py-1 rounded-full ${meta[2]}`}>{meta[0]} {meta[1]}</span><span className="truncate"><i className="not-italic text-white/40">Customer:</i> {current.customerId.name}</span><span className="truncate"><i className="not-italic text-white/40">Restaurant:</i> {current.restaurantId.name}</span><span><i className="not-italic text-white/40">Total:</i> ৳{current.orderId.totalAmount}</span><span><i className="not-italic text-white/40">Order Time:</i> {new Date(current.orderId.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</span></div>})()}
  <section className="flex-1 overflow-y-auto p-4 space-y-2">{hasMore&&<button onClick={more} className="block mx-auto text-xs text-primary-400">Load earlier messages</button>}{messages.map(m=>{const mine=m.senderRole===(restaurantMode?'restaurant':'user');const day=new Date(m.createdAt).toDateString();const separator=day!==lastDay;lastDay=day;return <React.Fragment key={m._id}>{separator&&<div className="text-center text-xs text-white/35 py-3"><span className="bg-dark-200 px-3 py-1 rounded-full">{new Date(m.createdAt).toLocaleDateString()}</span></div>}<div className={`flex ${mine?'justify-end':'justify-start'} group`}><div className={`max-w-[82%] sm:max-w-[68%] rounded-2xl px-3 py-2 ${mine?'bg-primary-500 rounded-br-sm':'bg-white/10 rounded-bl-sm'}`}>{m.replyTo&&<div className="border-l-2 border-white/40 pl-2 mb-2 text-xs opacity-70 truncate">{m.replyTo.message||'📷 Image'}</div>}{m.imageUrl&&<img src={m.imageUrl} className="max-h-64 rounded-xl mb-2 object-cover"/>}{m.message&&<p className="whitespace-pre-wrap break-words">{m.message}</p>}<div className="flex justify-end items-center gap-1 text-[10px] opacity-60 mt-1">{new Date(m.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}{mine&&(m.isRead?<CheckCheck className="w-3 text-blue-200"/>:<Check className="w-3"/>)}</div></div><button onClick={()=>setReply(m)} className="opacity-0 group-hover:opacity-60 p-2"><Reply className="w-4"/></button></div></React.Fragment>})}{otherTyping&&<div className="text-xs text-white/45 animate-pulse">Typing…</div>}<div ref={bottom}/></section>
  {current.isBlocked?<div className="p-4 border-t border-white/10 text-center text-sm text-red-300 bg-red-500/10">{restaurantMode?'Unblock this customer to resume messaging.':'You can no longer send messages to this restaurant.'}</div>:<footer className="p-3 border-t border-white/10">{reply&&<div className="mb-2 px-3 py-2 rounded-lg bg-white/5 text-xs flex justify-between">Replying to: {reply.message||'📷 Image'}<button onClick={()=>setReply(undefined)}>×</button></div>}<div className="flex items-end gap-2 relative"><button onClick={()=>setEmoji(!emoji)} className="p-2 text-white/60"><Smile/></button>{emoji&&<div className="absolute bottom-12 left-0 card p-2 grid grid-cols-4 gap-1">{emojis.map(e=><button key={e} onClick={()=>{type(text+e);setEmoji(false)}} className="text-xl p-1">{e}</button>)}</div>}<label className={`p-2 cursor-pointer ${uploading?'opacity-40':''}`}><ImagePlus/><input type="file" accept="image/jpeg,image/png,image/webp" className="hidden" disabled={uploading} onChange={e=>image(e.target.files?.[0])}/></label><textarea value={text} onChange={e=>type(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();submit()}}} className="input min-h-11 max-h-28 resize-none flex-1" placeholder="Write a message…" maxLength={2000}/><button onClick={submit} disabled={sending||!text.trim()} className="btn btn-primary p-3"><Send className="w-5"/></button></div></footer>}</main>}
 </div>;
};export default MessagingPage;
