import React,{useState} from 'react';
import { BadgePercent, Save, Trash2, TrendingUp, Wallet } from 'lucide-react';
import toast from 'react-hot-toast';
import { useDeleteCommissionSettingMutation, useGetAdminRestaurantsQuery, useGetCommissionQuery, useSaveScopedCommissionMutation } from '../../store/api/adminApi';
import type { CommissionMode, CommissionScope } from '../../store/api/adminApi';

const money=(n=0)=>`৳${n.toLocaleString(undefined,{maximumFractionDigits:0})}`;
const CommissionSettingsPage:React.FC=()=>{
 const [page,setPage]=useState(1); const {data,isLoading}=useGetCommissionQuery({page,limit:20}); const {data:restaurantData}=useGetAdminRestaurantsQuery({limit:100});
 const [save,{isLoading:saving}]=useSaveScopedCommissionMutation(); const [remove]=useDeleteCommissionSettingMutation();
 const [form,setForm]=useState<{mode:CommissionMode;value:number;scope:CommissionScope;restaurant:string;category:string;city:string;reason:string}>({mode:'percentage',value:5,scope:'global',restaurant:'',category:'',city:'',reason:''}); const d=data?.data;
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{await save(form).unwrap();toast.success('Commission setting saved');setForm(x=>({...x,reason:''}));}catch(err:any){toast.error(err?.data?.message||'Unable to save commission');}};
 return <div className="space-y-6"><header><p className="text-sm font-semibold text-primary-300">Platform finance</p><h1 className="text-3xl font-black">Commission Management</h1><p className="mt-2 text-white/50">Control the default 5% commission and targeted restaurant overrides.</p></header>
 <div className="grid gap-4 sm:grid-cols-3">{[['Total Platform Revenue',d?.analytics.totalPlatformRevenue||0,Wallet],['Today’s Commission',d?.analytics.todayCommission||0,BadgePercent],['Monthly Commission',d?.analytics.monthlyCommission||0,TrendingUp]].map(([label,value,Icon]:any)=><div key={label} className="card p-5"><Icon className="h-5 w-5 text-primary-400"/><p className="mt-4 text-sm text-white/45">{label}</p><b className="mt-1 block text-2xl">{money(value)}</b></div>)}</div>
 <form onSubmit={submit} className="card grid gap-4 p-6 md:grid-cols-2 xl:grid-cols-4"><label><span className="text-sm text-white/55">Commission Mode</span><select className="input mt-2 w-full" value={form.mode} onChange={e=>setForm({...form,mode:e.target.value as CommissionMode,value:e.target.value==='none'?0:form.value})}><option value="percentage">Percentage</option><option value="fixed">Fixed Amount / Order</option><option value="none">No Commission</option></select></label><label><span className="text-sm text-white/55">Value</span><div className="relative mt-2"><input className="input w-full" type="number" min="0" max={form.mode==='percentage'?100:100000} disabled={form.mode==='none'} value={form.value} onChange={e=>setForm({...form,value:Number(e.target.value)})}/><span className="absolute right-3 top-3 text-white/40">{form.mode==='percentage'?'%':'৳'}</span></div></label><label><span className="text-sm text-white/55">Scope</span><select className="input mt-2 w-full" value={form.scope} onChange={e=>setForm({...form,scope:e.target.value as CommissionScope})}><option value="global">Apply Globally</option><option value="restaurant">Selected Restaurant</option><option value="category">Restaurant Category</option><option value="city">City</option></select></label>{form.scope==='restaurant'?<label><span className="text-sm text-white/55">Restaurant</span><select required className="input mt-2 w-full" value={form.restaurant} onChange={e=>setForm({...form,restaurant:e.target.value})}><option value="">Select restaurant</option>{restaurantData?.data?.restaurants.map(r=><option key={r._id} value={r._id}>{r.name} ({r.restaurantId||r._id.slice(-6)})</option>)}</select></label>:form.scope==='category'?<label><span className="text-sm text-white/55">Category / Cuisine</span><input required className="input mt-2 w-full" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label>:form.scope==='city'?<label><span className="text-sm text-white/55">City</span><input required className="input mt-2 w-full" value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label>:<div/>}<label className="md:col-span-2 xl:col-span-3"><span className="text-sm text-white/55">Reason for Change</span><input required maxLength={500} className="input mt-2 w-full" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Required for the audit history"/></label><button disabled={saving} className="btn btn-primary self-end"><Save className="mr-2 h-4 w-4"/>{saving?'Saving…':'Save Commission'}</button></form>
 <section className="card overflow-hidden"><div className="border-b border-white/10 p-5"><h2 className="text-xl font-bold">Active Commission Rules</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-white/[.03] text-left text-white/40"><tr>{['Scope','Target','Mode','Value','Changed By','Reason',''].map(x=><th className="px-5 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{d?.settings.map(x=><tr className="border-t border-white/5" key={x._id}><td className="px-5 py-4 capitalize">{x.scope}</td><td className="px-5 py-4">{x.scope==='global'?'All Restaurants':x.restaurant?.name||x.category||x.city}</td><td className="px-5 py-4 capitalize">{x.mode}</td><td className="px-5 py-4 font-bold text-primary-300">{x.mode==='none'?'None':x.mode==='percentage'?`${x.value}%`:money(x.value)}</td><td className="px-5 py-4">{x.updatedBy?.name||'Admin'}</td><td className="max-w-xs truncate px-5 py-4 text-white/50">{x.reason}</td><td className="px-5 py-4">{x.scope!=='global'&&<button onClick={async()=>{if(confirm('Remove this override?'))try{await remove(x._id).unwrap();toast.success('Override removed');}catch(e:any){toast.error(e?.data?.message||'Unable to remove')}}} className="rounded-lg p-2 text-red-300 hover:bg-red-500/10" aria-label="Remove override"><Trash2 className="h-4 w-4"/></button>}</td></tr>)}</tbody></table></div>{isLoading&&<p className="p-8 text-center text-white/40">Loading commission rules…</p>}</section>
 <div className="grid gap-6 xl:grid-cols-2"><section className="card p-5"><h2 className="text-xl font-bold">Top Revenue Restaurants</h2><div className="mt-4 space-y-3">{d?.analytics.topRevenue.map((x,i)=><div key={String(x.restaurantId)} className="flex justify-between rounded-xl bg-white/[.03] p-3"><span>#{i+1} {x.name||'Deleted Restaurant'}</span><b>{money(x.gross)}</b></div>)}</div></section><section className="card p-5"><h2 className="text-xl font-bold">Highest Commission Restaurants</h2><div className="mt-4 space-y-3">{d?.analytics.highestCommission.map((x,i)=><div key={String(x.restaurantId)} className="flex justify-between rounded-xl bg-white/[.03] p-3"><span>#{i+1} {x.name||'Deleted Restaurant'}</span><b>{money(x.commission)}</b></div>)}</div></section></div>
 <section className="card overflow-hidden"><div className="p-5"><h2 className="text-xl font-bold">Commission History</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-white/[.03] text-left text-white/40"><tr>{['Date','Scope','Target','Old','New','Changed By','Reason'].map(x=><th className="px-5 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{d?.history.map(x=><tr key={x._id} className="border-t border-white/5"><td className="px-5 py-4">{new Date(x.createdAt).toLocaleString()}</td><td className="px-5 py-4 capitalize">{x.scope}</td><td className="px-5 py-4">{x.target}</td><td className="px-5 py-4">{x.oldMode?`${x.oldValue}${x.oldMode==='percentage'?'%':' BDT'}`:'—'}</td><td className="px-5 py-4">{x.newMode==='none'?'None':`${x.newValue}${x.newMode==='percentage'?'%':' BDT'}`}</td><td className="px-5 py-4">{x.changedBy?.name||'Admin'}</td><td className="px-5 py-4 text-white/50">{x.reason}</td></tr>)}</tbody></table></div>{(d?.pagination.pages||0)>1&&<div className="flex justify-center gap-4 border-t border-white/5 p-4"><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="btn btn-ghost">Previous</button><span className="py-3 text-sm">{page} / {d?.pagination.pages}</span><button disabled={page===(d?.pagination.pages||1)} onClick={()=>setPage(p=>p+1)} className="btn btn-ghost">Next</button></div>}</section>
 </div>;
};
export default CommissionSettingsPage;
