import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Activity, ArrowLeft, Ban, Clock, Download, Power, ShoppingBag, Star, Store, Wallet } from 'lucide-react';
import toast from 'react-hot-toast';
import { BarChart, DonutChart } from '../../components/restaurant/AnalyticsCharts';
import { useGetAdminRestaurantAnalyticsQuery, useUpdateAdminRestaurantStatusMutation } from '../../store/api/adminApi';
import RestaurantCommissionPanel from '../../components/admin/RestaurantCommissionPanel';

const money=(value=0)=>`৳${value.toLocaleString(undefined,{maximumFractionDigits:0})}`;
const hours=(minutes=0)=>`${(minutes/60).toFixed(1)}h`;
const Stat:React.FC<{label:string;value:string|number}>=({label,value})=><div className="rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-xs text-white/45">{label}</p><b className="mt-2 block text-xl">{value}</b></div>;
const Section:React.FC<React.PropsWithChildren<{title:string;icon?:React.ReactNode}>>=({title,icon,children})=><section className="card p-5 sm:p-6"><h2 className="mb-5 flex items-center gap-2 text-xl font-bold">{icon}{title}</h2>{children}</section>;

const RestaurantDetailsPage:React.FC=()=>{
 const {restaurantId=''}=useParams(); const navigate=useNavigate();
 const[detailView,setDetailView]=useState<'overview'|'commission'|'payments'>('overview');
 const {data,isLoading,error}=useGetAdminRestaurantAnalyticsQuery(restaurantId,{skip:!restaurantId});
 const [updateStatus,{isLoading:isUpdating}]=useUpdateAdminRestaurantStatusMutation(); const d=data?.data;
 const act=async(action:'activate'|'suspend'|'disable_ordering'|'enable_ordering'|'open'|'close')=>{if((action==='suspend'||action==='disable_ordering')&&!confirm(`Confirm ${action.replace('_',' ')}?`))return;try{await updateStatus({restaurantId,action}).unwrap();toast.success('Restaurant status updated');}catch(e:any){toast.error(e?.data?.message||'Status update failed');}};
 if(isLoading)return <div className="space-y-4">{Array.from({length:6}).map((_,i)=><div key={i} className="h-28 animate-pulse rounded-2xl bg-white/5"/>)}</div>;
 if(error||!d)return <div className="card p-12 text-center"><h2 className="text-xl font-bold">Restaurant performance unavailable</h2><button className="btn btn-primary mt-5" onClick={()=>navigate('/admin/restaurants')}>Back to Restaurants</button></div>;
 const r=d.restaurant,owner=r.owner; const statusStyles:Record<string,string>={active:'bg-green-500/15 text-green-300',closed:'bg-red-500/15 text-red-300',temporarily_closed:'bg-yellow-500/15 text-yellow-300',suspended:'bg-gray-500/20 text-gray-300'};
 const today=[['Revenue',money(d.today.revenue)],['Orders',d.today.orders],['Completed',d.today.completed],['Pending',d.today.pending],['Preparing',d.today.preparing],['Out for Delivery',d.today.outForDelivery],['Delivered',d.today.delivered],['Cancelled',d.today.cancelled],['Refunded',d.today.refunded],['Average Order',money(d.today.averageOrderValue)],['New Customers',d.today.newCustomers],['Reviews',d.today.reviews],['Average Rating',(d.today.averageRating||0).toFixed(1)]] as const;
 const statusValues=['pending','preparing','outForDelivery','delivered','cancelled'].map((key,i)=>({label:key.replace(/([A-Z])/g,' $1'),value:d.today[key]||0,color:['#eab308','#a855f7','#3b82f6','#22c55e','#ef4444'][i]}));
 return <div className="space-y-6 print:bg-white print:text-black">
  <header className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><button onClick={()=>navigate('/admin/restaurants')} className="rounded-xl bg-white/5 p-2" aria-label="Back"><ArrowLeft/></button><div><p className="text-sm text-primary-300">Restaurant monitoring</p><h1 className="text-3xl font-black">{r.name}</h1></div></div><button onClick={()=>window.print()} className="btn btn-ghost"><Download className="mr-2 h-4 w-4"/>Download PDF</button></header>
  <nav className="card flex gap-2 overflow-x-auto p-2" aria-label="Restaurant details sections">{(['overview','commission','payments'] as const).map(view=><button key={view} onClick={()=>setDetailView(view)} className={`rounded-xl px-4 py-2.5 text-sm font-medium capitalize transition ${detailView===view?'bg-primary-500 text-white':'text-white/55 hover:bg-white/5 hover:text-white'}`}>{view}</button>)}<button onClick={()=>navigate(`/admin/orders?restaurant=${r._id}`)} className="rounded-xl px-4 py-2.5 text-sm font-medium text-white/55 hover:bg-white/5 hover:text-white">Orders</button><button onClick={()=>{setDetailView('overview');setTimeout(()=>document.getElementById('restaurant-activity')?.scrollIntoView({behavior:'smooth'}),0)}} className="rounded-xl px-4 py-2.5 text-sm font-medium text-white/55 hover:bg-white/5 hover:text-white">Activity</button></nav>
  {detailView!=='overview'?<RestaurantCommissionPanel restaurantId={restaurantId} view={detailView}/>:<>
  <Section title="Restaurant Information" icon={<Store className="text-primary-400"/>}><div className="grid gap-6 lg:grid-cols-[240px_1fr]"><div><div className="relative h-36 overflow-hidden rounded-2xl bg-white/5"><img src={r.coverImage||r.image} className="h-full w-full object-cover"/><img src={r.image} className="absolute bottom-3 left-3 h-16 w-16 rounded-xl border-2 border-dark-100 object-cover"/></div></div><div className="grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-3"><p><span className="text-white/45">Restaurant ID</span><b className="block">{r.restaurantId||r._id}</b></p><p><span className="text-white/45">Owner</span><b className="block">{owner?.name||'Unavailable'}</b></p><p><span className="text-white/45">Owner Email</span><b className="block">{owner?.email||r.email}</b></p><p><span className="text-white/45">Phone</span><b className="block">{owner?.phone||r.phone}</b></p><p><span className="text-white/45">Registered</span><b className="block">{r.createdAt?new Date(r.createdAt).toLocaleDateString():'Unavailable'}</b></p><p><span className="text-white/45">Status</span><b className={`mt-1 inline-block rounded-full px-3 py-1 capitalize ${statusStyles[r.status]}`}>{r.status.replace('_',' ')}</b></p><p className="sm:col-span-2"><span className="text-white/45">Address</span><b className="block">{[r.address.restaurantAddress,r.address.street,r.address.city,r.address.state,r.address.country].filter(Boolean).join(', ')}</b></p><p><span className="text-white/45">Business Hours</span><b className="block">{r.openingHours?.filter(x=>!x.isClosed).slice(0,1).map(x=>`${x.open}–${x.close}`).join()||'Not configured'}</b></p></div></div></Section>
  <Section title="Today's Performance" icon={<Activity className="text-cyan-400"/>}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5">{today.map(([label,value])=><Stat key={label} label={label} value={value}/>)}</div></Section>
  <Section title="Earnings" icon={<Wallet className="text-green-400"/>}><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries({Gross:d.earnings.grossRevenue,'Platform Commission':d.earnings.platformCommission,'Net Earnings':d.earnings.netEarnings,Withdrawn:d.earnings.withdrawnAmount,'Pending Balance':d.earnings.pendingBalance,'Lifetime Revenue':d.earnings.lifetimeRevenue,'Lifetime Orders':d.earnings.lifetimeOrders}).map(([k,v])=><Stat key={k} label={k} value={k.includes('Orders')?v:money(v)}/>)}</div></Section>
  <Section title="Restaurant Activity" icon={<Clock className="text-violet-400"/>}><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{Object.entries({Current:d.activity.currentOnlineDuration,Today:d.activity.today,Yesterday:d.activity.yesterday,'This Week':d.activity.week,'This Month':d.activity.month,Lifetime:d.activity.lifetime}).map(([k,v])=><Stat key={k} label={k} value={hours(v)}/>)}</div></Section>
  <div className="grid gap-6 xl:grid-cols-2"><Section title="Orders per Day"><BarChart data={d.charts.daily.map(x=>({label:x._id.slice(5),value:x.orders}))}/></Section><Section title="Revenue per Day"><BarChart currency data={d.charts.daily.map(x=>({label:x._id.slice(5),value:x.revenue}))} color="#22c55e"/></Section><Section title="Daily Active Hours"><BarChart data={d.charts.activeDaily.map(x=>({label:x._id.slice(5),value:x.hours}))} color="#8b5cf6"/></Section><Section title="Monthly Active Hours"><BarChart data={d.charts.activeMonthly.map(x=>({label:x._id,value:x.hours}))} color="#a855f7"/></Section><Section title="Order Status Distribution"><DonutChart values={statusValues}/></Section><Section title="Completed vs Cancelled"><DonutChart values={[{label:'Completed',value:d.earnings.lifetimeOrders?Math.round(d.health.completionRate*d.earnings.lifetimeOrders/100):0,color:'#22c55e'},{label:'Cancelled',value:d.earnings.lifetimeOrders?Math.round(d.health.cancellationRate*d.earnings.lifetimeOrders/100):0,color:'#ef4444'}]}/></Section><Section title="Revenue per Month"><BarChart currency data={d.charts.monthly.map(x=>({label:`${x._id.month}/${String(x._id.year).slice(-2)}`,value:x.revenue}))}/></Section><Section title="Hourly Traffic / Peak Hours"><BarChart data={d.charts.hourly.map(x=>({label:`${x._id}:00`,value:x.orders}))} color="#06b6d4"/></Section><Section title="Customer Growth"><BarChart data={d.charts.daily.map(x=>({label:x._id.slice(5),value:x.customers?.length||0}))} color="#ec4899"/></Section></div>
  <Section title="Restaurant Health" icon={<Star className="text-yellow-300"/>}><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{Object.entries(d.health).map(([k,v])=><Stat key={k} label={k.replace(/([A-Z])/g,' $1')} value={k.toLowerCase().includes('time')?`${v.toFixed(0)} min`:k.toLowerCase().includes('rating')?v.toFixed(1):`${v.toFixed(1)}${k==='reviewCount'?'':'%'}`}/>)}</div></Section>
  <div id="restaurant-activity"><Section title="Recent Activities"><div className="space-y-0">{!d.activities.length&&<p className="py-8 text-center text-white/40">No activity has been recorded yet.</p>}{d.activities.map(x=><div key={x._id} className="relative border-l border-white/10 py-3 pl-6"><i className="absolute -left-1.5 top-5 h-3 w-3 rounded-full bg-primary-400"/><b className="capitalize">{x.type.replaceAll('_',' ')}</b><p className="text-sm text-white/55">{x.message}</p><small className="text-white/35">{new Date(x.occurredAt).toLocaleString()}{x.actor?.name?` · ${x.actor.name}`:''}</small></div>)}</div></Section></div>
  <Section title="Admin Controls"><div className="flex flex-wrap gap-3"><button disabled={isUpdating} onClick={()=>act(r.isActive?'suspend':'activate')} className="btn btn-ghost">{r.isActive?<Ban className="mr-2 h-4 w-4"/>:<Power className="mr-2 h-4 w-4"/>}{r.isActive?'Suspend Restaurant':'Activate Restaurant'}</button><button disabled={isUpdating} onClick={()=>act(r.acceptingOrders===false?'enable_ordering':'disable_ordering')} className="btn btn-ghost"><ShoppingBag className="mr-2 h-4 w-4"/>{r.acceptingOrders===false?'Enable Ordering':'Temporarily Disable Ordering'}</button><button onClick={()=>navigate(`/admin/orders?restaurant=${r._id}`)} className="btn btn-ghost">View Reports</button><button onClick={()=>navigate(`/admin/reviews?restaurant=${r._id}`)} className="btn btn-ghost">View Reviews & Complaints</button></div></Section>
  </>}
 </div>;
};
export default RestaurantDetailsPage;
