import React, { useState } from 'react';
import { Check, Clock3, Search, ShieldCheck, Store, X } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { useDecideNameChangeRequestMutation, useGetNameChangeRequestsQuery } from '../../store/api/restaurantIdentityApi';
import type { NameChangeStatus } from '../../store/api/restaurantIdentityApi';

const RestaurantNameChangeRequestsPage: React.FC = () => {
  const [status, setStatus] = useState<NameChangeStatus|''>('pending');
  const [search, setSearch] = useState('');
  const { data, isLoading } = useGetNameChangeRequestsQuery(status);
  const [decide, { isLoading: deciding }] = useDecideNameChangeRequestMutation();
  const rows = (data?.data || []).filter(row => `${row.restaurantId} ${row.oldName} ${row.requestedName} ${typeof row.requestedBy==='object'?`${row.requestedBy.name} ${row.requestedBy.email}`:''}`.toLowerCase().includes(search.toLowerCase()));
  const act = async (id:string, next:'approved'|'rejected') => { if (!window.confirm(`${next==='approved'?'Approve':'Reject'} this restaurant name change request?`)) return; try { await decide({id,status:next}).unwrap(); toast.success(`Request ${next}`); } catch(error:any) { toast.error(error?.data?.message || 'Decision failed'); } };
  return <div className="space-y-6"><header><p className="text-primary-400 font-medium">Secure identity administration</p><h1 className="text-3xl font-bold">Restaurant Name Change Requests</h1><p className="text-white/50 mt-2">Review verified owner requests and preserve a permanent audit trail.</p></header>
    <div className="card p-4 flex flex-col sm:flex-row gap-3"><label className="relative flex-1"><Search className="absolute left-3 top-3 w-5 h-5 text-white/35"/><input className="input pl-10" placeholder="Search ID, restaurant, owner, or email" value={search} onChange={e=>setSearch(e.target.value)}/></label><select className="input sm:w-48" value={status} onChange={e=>setStatus(e.target.value as NameChangeStatus|'')}><option value="">All statuses</option><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></div>
    {isLoading?<div className="card p-12 text-center">Loading requests…</div>:!rows.length?<div className="card p-12 text-center"><ShieldCheck className="w-12 h-12 mx-auto text-white/20"/><h2 className="font-semibold mt-4">No requests found</h2><p className="text-white/40 text-sm mt-1">Requests matching this view will appear here.</p></div>:<div className="grid gap-4">{rows.map(row=>{const owner=typeof row.requestedBy==='object'?row.requestedBy:null;return <article key={row._id} className="card p-5 border border-white/5"><div className="flex flex-col lg:flex-row lg:items-start gap-5"><div className="w-12 h-12 rounded-2xl bg-primary-500/15 text-primary-400 grid place-items-center"><Store/></div><div className="flex-1 grid sm:grid-cols-2 xl:grid-cols-4 gap-4"><div><small className="text-white/40">Restaurant ID</small><b className="block font-mono">{row.restaurantId}</b></div><div><small className="text-white/40">Current Name</small><b className="block">{row.oldName}</b></div><div><small className="text-white/40">Requested Name</small><b className="block text-primary-300">{row.requestedName}</b></div><div><small className="text-white/40">Status</small><span className={`block capitalize ${row.status==='pending'?'text-yellow-300':row.status==='approved'?'text-green-300':'text-red-300'}`}>{row.status}</span></div><div><small className="text-white/40">Owner</small><p>{owner?.name||'Unknown'}</p><p className="text-xs text-white/40">{owner?.email}</p></div><div><small className="text-white/40">Request Date</small><p>{new Date(row.requestedAt).toLocaleString()}</p></div>{row.approvalDate&&<div><small className="text-white/40">Decision Date</small><p>{new Date(row.approvalDate).toLocaleString()}</p></div>}<div className="sm:col-span-2 xl:col-span-4 rounded-xl bg-white/[0.03] p-3"><small className="text-white/40">Reason</small><p className="mt-1">{row.reason}</p></div></div>{row.status==='pending'&&<div className="flex lg:flex-col gap-2"><button disabled={deciding} onClick={()=>act(row._id,'approved')} className="btn bg-green-600 hover:bg-green-500"><Check className="w-4 h-4 mr-1"/>Approve</button><button disabled={deciding} onClick={()=>act(row._id,'rejected')} className="btn bg-red-600 hover:bg-red-500"><X className="w-4 h-4 mr-1"/>Reject</button></div>}</div></article>})}</div>}
    <p className="text-xs text-white/35 flex gap-2"><Clock3 className="w-4 h-4"/>All decisions retain requestor, approver, timestamps, old name, requested name, reason, and final status.</p>
  </div>;
};
export default RestaurantNameChangeRequestsPage;
